name: cross

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.19']
        go-package: ['.', './eventkitd']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - run: go vet ./...
      working-directory: ${{ matrix.go-package }}
    - run: go test -vet=off -v ./...
      working-directory: ${{ matrix.go-package }}

